### ISSUE TITLE
Can basilisk remove its old cache if a new version is available?

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/basilisk#46]
The basilisk cache can grow quite large. Is there a way that basilisk can remove the old cache before it creates a new cache for a new version of basilisk?

**Comment by LTLA** [comment]
It should already do so via **dir.expiry** functions. Whenever **basilisk** calls `dir.expiry::unlockDirectory()`, it will look through the older versions and attempt to remove them if they're older than a month. I can't remove them immediately because people might be running multiple R installations with different versions of **basilisk**.

**Comment by LTLA** [comment]
Note: you could adjust the `BIOC_DIR_EXPIRY_LIMIT` environment variable to a lower number of days - possibly zero - if you know that you will only ever need the latest version.
